version: '3.8'

services:
  frontend:
    image: frontend-blog-prod-image
    build:
      context: ./bloglist-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    container_name: frontend-blog-prod-container
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./blog/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./blog/mongo_data:/data/db
  backend:
    image: backend-blog-prod-image
    build:
      context: ./blog/
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3001:3000
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - DB_URL=${DB_URL}
      - SECRET=${SECRET}
    container_name: backend-blog-prod-container
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-3
    depends_on:
      - frontend
